import type { Metadata } from "next";
// Import the Metadata type from Next.js for type-checking metadata properties.

import { Inter } from "next/font/google";
// Import the Inter font from Google Fonts using the Next.js font loader.

import "./globals.css";
// Import global CSS styles.

import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
// Import the storyblokInit function and apiPlugin from the Storyblok React SDK.

import { StoryblokProvider } from "@/components/StoryblokProvider";
// Import a custom StoryblokProvider component from the local components directory.

import Link from "next/link";
// Import the Link component from Next.js for client-side navigation.

const inter = Inter({ subsets: ["latin"] });
// Initialize the Inter font with Latin subset.

export const metadata: Metadata = {
  // Define metadata for the application.
  title: "Create Next App",
  description: "Generated by create next app",
};

const cachedFetch = (input: any, init?: any): Promise<Response> => {
  // Define a cached fetch function to handle API requests with caching.
  return fetch(input, {
    ...init,
    cache: process.env.NODE_ENV === "development" ? "no-store" : "force-cache",
    // Use "no-store" cache policy in development for fresh data,
    // Use "force-cache" in production to cache responses.
  });
};

storyblokInit({
  // Initialize Storyblok with the provided configuration.
  accessToken: process.env.STORYBLOK_TOKEN,
  // Use the access token from environment variables for authentication.
  use: [apiPlugin],
  // Use the apiPlugin to enable API interactions.
  apiOptions: {
    fetch: cachedFetch,
    // Use the custom cached fetch function for API requests.
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Define the RootLayout component which wraps the entire application.
  
  return (
    <StoryblokProvider>
      {/* Wrap the application in the StoryblokProvider for context and state management. */}
      
      <html lang="en">
        {/* Set the language attribute for the HTML document to English. */}
        
        <body className={`${inter.className} bg-blue-50`}>
          {/* Apply the Inter font and a background color to the body element. */}
          
          <header>
            {/* Define the header section. */}
            
            <nav className="container mx-auto px-4 w-full py-8 flex justify-between">
              {/* Define a navigation bar with responsive styling. */}
              
              <Link href={"/"}>Home</Link>
              {/* Link to the home page. */}
              
              <Link href={"/tours"}>Tours</Link>
              {/* Link to the tours page. */}
            </nav>
          </header>
          
          {children}
          {/* Render the children components passed to the RootLayout. */}
        </body>
      </html>
    </StoryblokProvider>
  );
}